// Electronics
export const ELECTRONICS_LOADING = 'ELECTRONICS_LOADING';
export const ELECTRONICS_FAILED = 'ELECTRONICS_FAILED';
export const ADD_ELECTRONICS = 'ADD_ELECTRONICS';

// Stationary
export const STATIONARIES_LOADING= 'STATIONARIES_LOADING';
export const ADD_STATIONARIES = 'ADD_STATIONARIES ';
export const STATIONARIES_FAILED= 'STATIONARIES_FAILED';

//Refreshments
export const REFRESHMENTS_LOADING= 'REFRESHMENTS_LOADING';
export const ADD_REFRESHMENTS = 'ADD_REFRESHMENTS ';
export const REFRESHMENTS_FAILED= 'REFRESHMENTS_FAILED';